// AUTO-GENERATED by scripts/trim-cursor-sprites.ts — do not edit by hand.
// Run `bun run scripts/trim-cursor-sprites.ts` to regenerate after editing
// any SVG in cursor-sprites/.


export interface SpriteInfo {
  /** post-trim viewBox width (incl. 1u padding on each side) */
  width: number;
  /** post-trim viewBox height (incl. 1u padding on each side) */
  height: number;
  /** click anchor as fraction of the rendered sprite, from Recordly's filename */
  hotspot: { x: number; y: number };
}

export const SPRITE_INFO = {
  "arrow": { width: 770, height: 748, hotspot: { x: 0.34, y: 0.24 } },
  "grab": { width: 770, height: 748, hotspot: { x: 0.5, y: 0.5 } },
  "not-allowed": { width: 770, height: 748, hotspot: { x: 0.23, y: 0 } },
  "pointer": { width: 770, height: 748, hotspot: { x: 0.39, y: 0.26 } },
  "text": { width: 154.2852, height: 352.0603, hotspot: { x: 0.5, y: 0.5 } },
} as const satisfies Record<string, SpriteInfo>;
